### PR TITLE
Python 2/3 compatibility

### PR DESCRIPTION
**Pull request by return42**
@rfk: Hi Ryan, here is my third PR for Python 2/3 compatibility we discussed in [1].

[1] mozilla-services/syncserver#97 (comment)

'konfig' was already Py2&3 compatible. This PR is mainly to add the uniform boilerplate (Makefile) we used.

### CODE REVIEW

**Comment by rfk** [comment]
I'm going to flag @tarekziade for this one - Tarek, @return42 is working to bring all the python syncserver dependencies up to speed for running under python3, do you want to weigh in on this PR?

**Comment by return42** [comment]
@tarekziade FYI there is a parent repository for Mozilla-Cloud's Python 3 movement. May you like to have a look at the [README](https://github.com/return42/moz-cloud) / Thanks!

**Comment by tarekziade** [comment]
Really cool, let's merge this! 

@jvehent or @karlht can you make me an admin of my own project ? Thanks :)

**Comment by return42** [comment]
@tarekziade thanks for the merge.

**Pull request merged**
